###
GET http://patersontech.duckdns.org:1338/cpu/teardown

###
GET http://patersontech.duckdns.org:1338/cpu/setup

###
GET http://patersontech.duckdns.org:1338/cpu

###
POST http://patersontech.duckdns.org:1338/cpu
Content-Type: application/json

{
    "name": "AMD Ryzen 9 5950X",
    "brand": "AMD",
    "description": "The AMD Ryzen 9 5950X is a 16-core, 32-thread processor with a base clock of 3.4 GHz and a max boost clock of 4.9 GHz. It is built on the 7nm Zen 3 architecture and is compatible with AM4 motherboards. The 5950X has a TDP of 105W.",
    "socket": "AM4",
    "cores": "16",
    "threads": "32",
    "baseClock": "3.4 GHz",
    "boostClock": "4.9 GHz",
    "tdp": "105W",
    "integratedGraphics": "None",
    "photoURL1": "http://patersontech.duckdns.org:8043/images/0000J.jpeg",
    "photoURL2": "http://patersontech.duckdns.org:8043/images/0000K.jpeg",
    "photoURL3": "http://patersontech.duckdns.org:8043/images/0000L.jpeg",
    "photoURL4": "",
    "photoURL5": "",
    "microcenterLink": "https://www.microcenter.com/product/674524/amd-ryzen-9-5950x-vermeer-34ghz-16-core-am4-boxed-processor-heatsink-not-included",
    "amazonLink": "https://a.co/d/4DcAE1P",
    "neweggLink": "https://newegg.io/nca211bd3a",
    "bestbuyLink": "https://www.bestbuy.com/site/amd-ryzen-9-5950x-4th-gen-16-core-32-threads-unlocked-desktop-processor-without-cooler-black/6438941.p?skuId=6438941"
}

###
POST http://patersontech.duckdns.org:1338/cpu
Content-Type: application/json

{
    "name": "Intel Core i9-12900K",
    "brand": "Intel",
    "description": "The Intel Core i9-12900K is a 16-core, 24-thread processor with a base clock of 3.2 GHz and a max boost clock of 5.2 GHz. It is built on the 10nm Alder Lake architecture and is compatible with LGA 1700 motherboards. The 12900K has a TDP of 125W.",
    "socket": "LGA 1700",
    "cores": "16",
    "threads": "24",
    "baseClock": "3.2 GHz",
    "boostClock": "5.2 GHz",
    "tdp": "125W",
    "integratedGraphics": "Integrated Intel UHD Graphics",
    "photoURL1": "http://patersontech.duckdns.org:8043/images/0000M.jpeg",
    "photoURL2": "http://patersontech.duckdns.org:8043/images/0000N.jpeg",
    "photoURL3": "http://patersontech.duckdns.org:8043/images/0000O.jpeg",
    "photoURL4": "http://patersontech.duckdns.org:8043/images/0000P.jpeg",
    "photoURL5": "http://patersontech.duckdns.org:8043/images/0000Q.jpeg",
    "microcenterLink": "https://www.microcenter.com/product/641915/intel-core-i9-12900k-alder-lake-32ghz-sixteen-core-lga-1700-boxed-processor-heatsink-not-included",
    "amazonLink": "https://a.co/d/amnno8t",
    "neweggLink": "https://newegg.io/nc8bd1b2f4",
    "bestbuyLink": "https://www.bestbuy.com/site/intel-core-i9-12900k-desktop-processor-16-8p-8e-cores-up-to-5-2-ghz-unlocked-lga1700-600-series-chipset-125w-grey-black-gold/6483663.p?skuId=6483663"
}