###
GET http://patersontech.duckdns.org:1338/gpu/teardown

###
GET http://patersontech.duckdns.org:1338/gpu/setup

###
GET http://patersontech.duckdns.org:1338/gpu

###
POST http://patersontech.duckdns.org:1338/gpu
Content-Type: application/json

{
    "name": "NVIDIA GeForce RTX 3090 Founders Edition (Refurbished)",
    "brand": "NVIDIA",
    "description": "The NVIDIA GeForce RTX 3090 is a high-end graphics card with 24GB of GDDR6X memory. It features 10496 CUDA cores and a boost clock of 1695 MHz. The RTX 3090 is built on the Ampere architecture and supports real-time ray tracing and DLSS.",
    "chipset": "NVIDIA GeForce RTX 3090",
    "memory": "24GB GDDR6X",
    "tdp": "350W",
    "photoURL1": "http://patersontech.duckdns.org:8043/images/0000R.jpeg",
    "photoURL2": "http://patersontech.duckdns.org:8043/images/0000S.jpeg",
    "photoURL3": "http://patersontech.duckdns.org:8043/images/0000T.jpeg",
    "photoURL4": "http://patersontech.duckdns.org:8043/images/0000U.jpeg",
    "photoURL5": "http://patersontech.duckdns.org:8043/images/0000V.jpeg",
    "microcenterLink": "https://www.microcenter.com/product/677156/nvidia-geforce-rtx-3090-founders-edition-dual-fan-24gb-gddr6x-pcie-40-graphics-card-(refurbished)",
    "amazonLink": "https://a.co/d/6hwpKlj",
    "neweggLink": "https://newegg.io/nc8a8c95f7",
    "bestbuyLink": ""
}

###
POST http://patersontech.duckdns.org:1338/gpu
Content-Type: application/json

{
    "name": "GIGABYTE GeForce RTX 4080 Super WINDFORCE V2",
    "brand": "Gigabyte",
    "description": "The GIGABYTE GeForce RTX 4080 Super WINDFORCE V2 is a high-end graphics card with 12GB of GDDR6X memory. It features 8960 CUDA cores and a boost clock of 1800 MHz. The RTX 4080 Super is built on the Ampere architecture and supports real-time ray tracing and DLSS.",
    "chipset": "NVIDIA GeForce RTX 4080",
    "memory": "12GB GDDR6X",
    "tdp": "300W",
    "photoURL1": "http://patersontech.duckdns.org:8043/images/0000W.jpeg",
    "photoURL2": "http://patersontech.duckdns.org:8043/images/0000X.jpeg",
    "photoURL3": "http://patersontech.duckdns.org:8043/images/0000Y.jpeg",
    "photoURL4": "http://patersontech.duckdns.org:8043/images/0000Z.jpeg",
    "photoURL5": "http://patersontech.duckdns.org:8043/images/00010.jpeg",
    "microcenterLink": "https://www.microcenter.com/product/676365/gigabyte-nvidia-geforce-rtx-4080-super-windforce-v2-triple-fan-16gb-gddr6x-pcie-40-graphics-card",
    "amazonLink": "https://a.co/d/fjISrjt",
    "neweggLink": "https://newegg.io/nc249d390c",
    "bestbuyLink": "https://www.bestbuy.com/site/gigabyte-nvidia-geforce-rtx-4080-super-windforce-v2-16gb-gddr6x-pci-express-4-0-graphics-card-black/6573357.p?skuId=6573357"
}