###
POST http://tower.local:1338/ram
Content-Type: application/json

{
    "name": "G.Skill Trident Z5 Neo RGB 64GB (2 x 32GB) DDR5-6000 - Black",
    "brand": "G.Skill",
    "description": "Trident Z5 Neo RGB DDR5 memory is designed for ultra-high overclocked performance on DDR5-enabled AMD platforms. Featuring AMD EXPO overclocking technology for easy memory overclocking on supported AMD platforms, the Trident Z5 Neo RGB series is the ideal choice for building high-performance systems.",
    "dims": "2",
    "speed": "6000 MT/S",
    "ddrClass": "DDR5",
    "capacity": "64GB",
    "photoURL": "http://tower.local:8043/images/00001.jpeg",
    "microcenterLink": "https://www.microcenter.com/product/664697/gskill-trident-z5-neo-rgb-64gb-(2-x-32gb)-ddr5-6000-pc5-48000-cl30-dual-channel-desktop-memory-kit-f5-6000j3040g32gx2-tz5nr-black",
    "amazonLink": "https://www.amazon.com/G-Skill-Trident-288-Pin-CL30-40-40-96-F5-6000J3040G32GX2-TZ5NR/dp/B0BJNTLJ5X/ref=sr_1_3?crid=2GCEN58343D63&dib=eyJ2IjoiMSJ9.RzLBBKFNRzQXjd73Vwr-P2fABy7NakTzizVwHrWxTiH4w0pg2oSpetcVbRNGbhwGuRtcNrKvsC7C6oMZ68iXoB4jNNlmQNg947mARWIL17vNymvlg-Ekty7lw7LCyR4-oFzLLhPwfsdMuxhxZrrD_GBgmQeRPcztBodCtFBf3O8ISlB-L6ZMVlRB52h7fNeysgK6qDd7YJdrD8yklwaYUdUJHFY7NBOFJlQnPcLGZ60.UDU8r4aw9gujcjy59yWnaz0_KJsaGF-ljDFRakCU35c&dib_tag=se&keywords=G.Skill%2BTrident%2BZ5%2BNeo%2BRGB%2B64GB%2B(2%2Bx%2B32GB)%2BDDR5-6000%2BCL30&qid=1720961551&sprefix=g.skill%2Btrident%2Bz5%2Bneo%2Brgb%2B64gb%2B2%2Bx%2B32gb%2Bddr5-6000%2Bcl30%2Caps%2C72&sr=8-3&th=1",
    "neweggLink": "https://www.newegg.com/g-skill-64gb/p/N82E16820374445",
    "bestbuyLink": ""
}

###
GET http://tower.local:1338/ram/setup

###
GET http://tower.local:1338/ram

###
GET http://tower.local:1338/ram/teardown